## Reto 3: `merge` para completar información faltante

### 1. Objetivos:
    - Completar la tabla `users` usando la información contenida en las tablas `occupations` y `age_ranges`.
    
---
    
### 2. Desarrollo:

#### a) Complementado información usando el método `merge`

No es muy práctico tener las tablas `occupations` y `age_range` por sí solas, ya que la información que contienen está íntimamente relacionada con al información de la tabla `users`. Vamos entonces a unir las tres tablas en una sola tabla para tener esa información mucho más accesible. Tu Reto consiste en los siguientes pasos:

1. Lee tus archivos `users`, `occupations` y `age_range` (o como sea que les quisiste llamar) y conviértelos en `DataFrames`.
2. Utiliza el método `merge` para agregar la información contenida en la tabla `occupations` a la tabla `users`.
3. Utiliza el método `merge` para agregar la información contenida en la tabla `age_ranges` a la tabla `users`.
4. Si lo consideras necesario, renombra y reordena las columnas para que la información sea clara.
5. Guarda tu nuevo conjunto de datos en un nuevo archivo .csv.

In [2]:
!pip install mysql-connector-python
import pandas as pd
import numpy as np
import mysql.connector

from google.colab import drive
drive.mount('/content/drive')

Collecting mysql-connector-python
  Downloading mysql_connector_python-8.1.0-cp310-cp310-manylinux_2_17_x86_64.whl (27.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.5/27.5 MB 19.0 MB/s eta 0:00:00
Collecting protobuf<=4.21.12,>=4.21.1 (from mysql-connector-python)
  Downloading protobuf-4.21.12-cp37-abi3-manylinux2014_x86_64.whl (409 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 409.8/409.8 kB 6.0 MB/s eta 0:00:00
Installing collected packages: protobuf, mysql-connector-python
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
Successfully installed mysql-connector-python-8.1.0 protobuf-4.21.12
Mounted at /content/drive

In [3]:
users = pd.read_csv('/content/drive/MyDrive/DataScience/users.csv',sep='\t').drop('Unnamed: 0',axis='columns')
users

      userID gender  age  occupation    zip
0          1      F    1          10  48067
1          2      M   56          16  70072
2          3      M   25          15  55117
3          4      M   45           7  02460
4          5      M   25          20  55455
...      ...    ...  ...         ...    ...
6035    6036      F   25          15  32603
6036    6037      F   45           1  76006
6037    6038      F   56           1  14706
6038    6039      F   45           0  01060
6039    6040      M   25           6  11106

[6040 rows x 5 columns]

In [4]:
ages = pd.read_csv('/content/drive/MyDrive/DataScience/age_ranges.csv',sep='\t').drop('Unnamed: 0',axis='columns')
occupations = pd.read_csv('/content/drive/MyDrive/DataScience/occupations.csv',sep='\t').drop('Unnamed: 0',axis='columns')

ageDict = ages.to_dict()['ageRange']
occDict = occupations.to_dict()['description']

users['age'] = users['age'].replace(ageDict)
users['occupation'] = users['occupation'].replace(occDict)

users

      userID gender    age              occupation    zip
0          1      F  18-24            K-12 student  48067
1          2      M     56           self-employed  70072
2          3      M     25               scientist  55117
3          4      M     45    executive/managerial  02460
4          5      M     25                  writer  55455
...      ...    ...    ...                     ...    ...
6035    6036      F     25               scientist  32603
6036    6037      F     45       academic/educator  76006
6037    6038      F     56       academic/educator  14706
6038    6039      F     45  other or not specified  01060
6039    6040      M     25      doctor/health care  11106

[6040 rows x 5 columns]

In [ ]:
users.to_csv('/content/drive/MyDrive/DataScience/usersMerged.csv',sep='\t',encoding='utf-8')

Compara tus resultados con tus compañeros y tu experta para asegurarse de que todos tengan un conjunto similar que contenga toda la información requerida.